/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3D/animal+cell+3d+model.glb -o animal-cell.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['tripo_node_0624d418-5c0a-42de-a722-25d8e1e37fd1']: THREE.Mesh
  }
  materials: {
    ['tripo_mat_0624d418-5c0a-42de-a722-25d8e1e37fd1']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/animal+cell+3d+model.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_0624d418-5c0a-42de-a722-25d8e1e37fd1'].geometry} material={materials['tripo_mat_0624d418-5c0a-42de-a722-25d8e1e37fd1']} />
    </group>
  )
}

useGLTF.preload('/animal+cell+3d+model.glb')
